-keep class com.tencent.smh_flutter_beacon_plugin.** { *; }
-keep class com.tencent**qimei.** { *;}
-keep class com.tencent.qimei.** { *;}
-keep class com.tencent.qmsp.oaid2.** {*;}
-keep class com.tencent.beacon.** { *;}